name: Docker Compose Build and Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker-compose.yml
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/uks-tim5:latest

      - name: Deploy Docker image to environment
        uses: docker/compose-action@1.2.1
        with:
          compose-file: docker-compose.yml
          project-name: uks-tim5
          log-driver: 'json-file'
          log-opt: |
            max-size=10m
            max-file=3